# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190523_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_name',
            new_name='author',
        ),
    ]
