# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('noob', 'noob'), ('student', 'student'), ('pro', 'pro')], default='student', max_length=20),
        ),
    ]
