# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190528_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('noob', 'noob'), ('student', 'student'), ('mid', 'mid'), ('pro', 'pro')], default='student', max_length=20),
        ),
    ]
