# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190529_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/images/profile.jpeg', upload_to='images'),
        ),
    ]
