# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-12 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190529_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
    ]
