# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugfix', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugtable',
            old_name='status',
            new_name='bug_fixed',
        ),
        migrations.AddField(
            model_name='bugtable',
            name='fixing_in_process',
            field=models.BooleanField(default=False),
        ),
    ]
