# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugfix', '0002_auto_20190422_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugtable',
            name='bug_solution',
            field=models.TextField(default=False),
        ),
    ]
