# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 17:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugfix', '0003_bugtable_bug_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugtable',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bugtable',
            name='bug_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bugtable',
            name='bug_solution',
            field=models.TextField(blank=True),
        ),
    ]
