# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 17:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugfix', '0004_auto_20190425_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugtable',
            name='date_pub',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='bugtable',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
