# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugfix', '0005_auto_20190425_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugtable',
            name='date_pub',
        ),
        migrations.AddField(
            model_name='bugtable',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bugtable',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
