# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugfix', '0006_auto_20190425_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugtable',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
