# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugfix', '0007_auto_20190425_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugtable',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
