# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugfix', '0008_auto_20190425_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugtable',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='bugtable',
            name='published_date',
        ),
        migrations.AddField(
            model_name='bugtable',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
