# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugfix', '0009_auto_20190425_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugtable',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
