# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugfix', '0010_bugtable_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.CharField(max_length=10)),
                ('votes', models.IntegerField(default=0)),
                ('bug_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugfix.BugTable')),
            ],
        ),
    ]
