# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugfix', '0011_upvote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upvote',
            old_name='likes',
            new_name='like_dislike',
        ),
    ]
