# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugfix', '0012_auto_20190430_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='bug_vote',
        ),
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
