# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 18:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugfix', '0013_auto_20190430_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugtable',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
