# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugfix', '0014_bugtable_upvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugtable',
            name='upvote',
        ),
    ]
