# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-02 18:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugfix', '0017_auto_20190501_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='like_text',
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
