# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-03 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugfix', '0023_auto_20190503_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugtable',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='bugtable',
            name='likes',
        ),
    ]
