# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-03 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugfix', '0025_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='votes',
            new_name='vote',
        ),
    ]
