# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugfix', '0028_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='bug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_set', to='bugfix.BugTable'),
        ),
    ]
