# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugfix', '0030_auto_20190504_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='bug',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
