# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugfix', '0034_auto_20190504_1658'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='bug',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bugtable',
            name='votes',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
