# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugfix', '0036_bugtable_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugtable',
            old_name='likes',
            new_name='vote',
        ),
    ]
