# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugfix', '0037_auto_20190506_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='bugtable',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugfix.Vote'),
        ),
    ]
