# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugfix', '0038_auto_20190506_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugtable',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
