# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugfix', '0042_auto_20190506_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_text',
            field=models.CharField(default='Like it', max_length=10),
        ),
    ]
