# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugfix', '0049_auto_20190506_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugtable',
            name='bug_fixed',
        ),
        migrations.RemoveField(
            model_name='bugtable',
            name='fixing_in_process',
        ),
    ]
