# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugfix', '0050_auto_20190507_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugtable',
            name='status',
            field=models.CharField(choices=[('bug_posted', 'bug_posted'), ('fixing_in_process', 'fixing_in_process'), ('bug_fixed', 'bug_fixed')], default='bug_posted', max_length=15),
        ),
    ]
