# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-11 14:00
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugfix', '0052_auto_20190507_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugtable',
            name='vote',
            field=models.IntegerField(default=0, verbose_name=django.contrib.auth.models.User),
        ),
    ]
