# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugfix', '0053_auto_20190511_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugtable',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
