# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugfix', '0056_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='bug',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
