# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190416_1655'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Feature',
        ),
    ]
