# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190416_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='image',
            field=models.ImageField(default='images/default.jpeg', upload_to='images'),
        ),
    ]
