# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_feature_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
