# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190430_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='tags',
            field=models.CharField(choices=[('all', 'all'), ('security', 'security'), ('pcb', 'pcb'), ('passive', 'passive')], default='all', max_length=20),
        ),
    ]
