# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_feature_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='tags',
        ),
    ]
