# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-06 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_feature_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(default='', max_length=15),
        ),
    ]
